# Generated by Django 4.1.7 on 2023-03-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_domainmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomainModel',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='schema_name',
        ),
        migrations.RemoveField(
            model_name='restaurantdomain',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='restaurantdomain',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='restaurantdomain',
            name='domain',
            field=models.CharField(max_length=255),
        ),
    ]
